name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the 'release' branch
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  test-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up JDK
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Run unit tests
      - name: Run tests
        run: ./gradlew test --parallel